name: Coolify Deploy

on:
  push:
    branches: [stage]
  workflow_dispatch:
    # inputs:
    #   environment:
    #     description: "Environment to deploy"
    #     required: true
    #     default: "stage"
    #     type: choice
    #     options:
    #       - production
    #       - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: stage
    steps:
      - name: GitHub Action - Deploy and Update ENVs on Coolify
        uses: devevandro/coolify-app-deploy@v0.0.1
        with:
          coolify_url: ${{ secrets.COOLIFY_URL }}
          coolify_token: ${{ secrets.COOLIFY_TOKEN }}
          coolify_app_uuid: ${{ secrets.COOLIFY_APP_UUID }}
          secrets: ${{ toJson(secrets) }}
    # - uses: actions/checkout@v4

    # - name: Setup Node.js
    #   uses: actions/setup-node@v4
    #   with:
    #     node-version: "20"

    # - name: Install Dependencies
    #   run: npm install @actions/core @actions/github axios

    # - name: Deploy to Coolify
    #   uses: actions/github-script@v7
    #   with:
    #     script: |
    #       const script = require('.github/scripts/deploy.js')
    #       await script({github, context, core})
    #   env:
    #     COOLIFY_URL: ${{ secrets.COOLIFY_URL }}
    #     COOLIFY_TOKEN: ${{ secrets.COOLIFY_TOKEN }}
    #     COOLIFY_APP_UUID: ${{ secrets.COOLIFY_APP_UUID }}
    #     SECRETS: ${{ toJson(secrets) }}
    # EXCLUDE: '["COOLIFY_URL", "CASLDCRTAPIDEVEASTUS2001_AZURE_SUBSCRIPTION_ID", "CASLDCRTAPIDEVEASTUS2001_REGISTRY_PASSWORD", "CASLDCRTAPIDEVEASTUS2001_AZURE_TENANT_ID", "CASLDCRTAPIPRODEASTUS2001_AZURE_TENANT_ID", "CASLDCRTAPIPRODEASTUS2001_REGISTRY_PASSWORD", "CASLDCRTAPIPRODEASTUS2001_REGISTRY_USERNAME", "CASLDCRTAPIDEVEASTUS2001_REGISTRY_USERNAME", "github_token", "CASLDCRTAPIPRODEASTUS2001_AZURE_SUBSCRIPTION_ID", "COOLIFY_TOKEN", "COOLIFY_APP_UUID", "CASLDCRTAPIPRODEASTUS2001_AZURE_CLIENT_ID", "CASLDCRTAPIDEVEASTUS2001_AZURE_CLIENT_ID", "GLOBAL_MONGO_URL_PROD", "GLOBAL_MONGO_URL_STAGING", "NPM_TOKEN", "TEST_GLOBAL"]'
